### ISSUE TITLE
traviora databse

### ISSUE THREAD

**Issue by putrapuices** [mastuyink/traviora#1]
kakak minta databse traviorany dong kak/...?
oya kak..gmn jalankan dynamicform ulpload file kak..?

**Comment by mastuyink** [comment]
mohon maaf ya kak kalau database belum bisa saya share karena itu project
kantor.
tapi kalau mau diskusi php khususnya yii2 mungkin bisa belajar bareng..,
terimakasih...


Pada tanggal Rab, 25 Mar 2020 pukul 12.25 putrapuices <
notifications@github.com> menulis:

**Comment by putrapuices** [comment]
kak minta bantuanny dong memasang user management di yii2 menggunakan dektrium, dan verifikasi emal dengan signupny kak

**Comment by mastuyink** [comment]
Kalau dektrium saya belum pernah  nyoba ya, harusnya di dokumentasinya kan
sudah ada panduannya, kalau signup confirm via email itu bisa diakali
dengab set defaukt user status ke innactive/disable, terus pas user signup
kirim email berisi verivikasi token, caranya bisa copas dari methos forgot
pasdword dari yii2 yang advanced template. Semoga membantu, maaf kalau agak
slow respon

**Comment by putrapuices** [comment]
Kakk..saya lagi belajar yii2 kak...klu kakak user management giman carany
kak..trus kalau untuk buat signup dengan email dan bebarap lainny gmn jug
kak...bs kah saya mnt w.a atau no hp kakak..saya kepengen kali belajar sm
kakk

Pada tanggal Rab, 20 Mei 2020 20.04, Mastuyink Abdul Aziz <
notifications@github.com> menulis:

**Comment by mastuyink** [comment]
bisa wa saya di 082234916187


Pada tanggal Rab, 20 Mei 2020 pukul 21.26 putrapuices <
notifications@github.com> menulis:
